### ISSUE TITLE
citar docs in emacs manual

### ISSUE THREAD

**Issue by tabroughton** [emacs-citar/citar#772] opened 2023-04-02 17:22 UTC
`C-h i m citar` returns no results - I was wondering if the docs are within emacs, I believe one of the greatest thing about linux and emacs is the nature of the manual/ documenting - eg. you don't have to search the internet to find out how to use something once you've installed it, you should be able to read it within the system.  But I can't find `citar` manual, does it exist?  if not would you like some help making and maintaining one maybe? (I've never done that but I'd be happy to give it a go).

**Comment by bdarcus** [comment] 2023-04-02 17:48
No, there's none, for no good reason other than I haven't done it, and wasn't sure either how.

> if not would you like some help making and maintaining one maybe? (I've never done that but I'd be happy to give it a go).

Yes please!

I have an open issue for this (#636), with some preliminary notes on how we might do this, so give it a shot, and if you come up with something, open up a PR?

I'm going to close this issue as a duplicate of #636. Please followup over there?

**Closed by bdarcus** 2023-04-02 17:48 UTC
Labels: enhancement
